// <auto-generated />
using Election.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Election.Migrations
{
    [DbContext(typeof(ElectionContext))]
<<<<<<<< HEAD:Election/Migrations/20220930235725_Third.Designer.cs
    [Migration("20220930235725_Third")]
    partial class Third
========
    [Migration("20220929232847_First")]
    partial class First
>>>>>>>> 402b9ec68971fc9f9c1918487364131d26296c21:Election/Migrations/20220929232847_First.Designer.cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Election.Entities.Politician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:Election/Migrations/20220930235725_Third.Designer.cs
                    b.HasKey("Id");

                    b.ToTable("Politicians");
========
                    b.Property<int>("PoliticiansNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("politician");
>>>>>>>> 402b9ec68971fc9f9c1918487364131d26296c21:Election/Migrations/20220929232847_First.Designer.cs
                });

            modelBuilder.Entity("Election.Entities.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

<<<<<<<< HEAD:Election/Migrations/20220930235725_Third.Designer.cs
                    b.Property<int>("PoliticianId")
                        .HasColumnType("int");

========
>>>>>>>> 402b9ec68971fc9f9c1918487364131d26296c21:Election/Migrations/20220929232847_First.Designer.cs
                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

<<<<<<<< HEAD:Election/Migrations/20220930235725_Third.Designer.cs
                    b.HasIndex("PoliticianId");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("Election.Entities.Voter", b =>
                {
                    b.HasOne("Election.Entities.Politician", "Politician")
                        .WithMany()
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");
========
                    b.ToTable("Person");
>>>>>>>> 402b9ec68971fc9f9c1918487364131d26296c21:Election/Migrations/20220929232847_First.Designer.cs
                });
#pragma warning restore 612, 618
        }
    }
}
